/* SEO 课程页 slug 定版映射 — URL 一旦发布不可更改,勿因课程改名而改 slug。
   gen-seo-block.js 与 gen-seo-pages.js 共用。 */
module.exports = {
  c2: "pot-odds-mdf",
  c3: "range-advantage",
  c4: "board-texture",
  c5: "cbet-in-position",
  c6: "cbet-defense",
  c7: "polarization-bluffcatch",
  c8: "indifference-mixed-strategy",
  c9: "turn-barrels",
  c10: "river-value-bluff",
  c11: "check-raise-probe",
  c12: "spr-commitment",
  c13: "bet-sizing-mdf",
  c14: "blockers",
  c15: "facing-raises",
  c16: "3bet-pots",
  c17: "pot-control",
  c18: "turn-defense",
  c19: "float-delayed-cbet",
  c20: "overbetting",
  c21: "donk-betting",
  c22: "thin-value",
  c23: "semi-bluff-draws",
  c24: "river-defense",
  c25: "multiway-pots",
  c26: "exploitative-adjustments",
  c27: "tournament-icm",
  c28: "multi-street-planning",
  c29: "special-boards",
  c30: "capstone-review",
};
