'use strict';
/*
 * seo-faq.js — 每课 2 条真问答(定义 + 实战),供 gen-seo-pages.js 生成可见 <details> FAQ + FAQPage JSON-LD。
 * 诚实红线:答案是正确的扑克事实,不编造数字/频率/评分。改动后重跑 node tools/gen-seo-pages.js。
 * 结构:{ <courseId>: [ {q:{en,zh}, a:{en,zh}}, ... ] }
 */
module.exports = {
  c2: [
    { q: { en: 'What are pot odds in poker?', zh: '什么是底池赔率?' },
      a: { en: 'Pot odds are the ratio of the current pot to the price of a call. Calling 40 into a pot of 120 lays 3:1, so you need about 25% equity to break even.',
           zh: '底池赔率是当前底池与跟注额的比值。跟 40 进 120 的底池是 3:1,大约需要 25% 胜率才不亏。' } },
    { q: { en: 'What is MDF (minimum defense frequency)?', zh: '什么是 MDF(最小防守频率)?' },
      a: { en: 'MDF is the share of your range you must continue with so a bettor can’t profitably bluff any two cards. It equals pot ÷ (pot + bet) — against a pot-sized bet, MDF is 50%.',
           zh: 'MDF 是你必须继续的范围比例,用来阻止对手用任意两张牌无脑诈唬盈利。等于 底池 ÷(底池+下注)—— 面对底池大小的下注,MDF 为 50%。' } },
  ],
  c3: [
    { q: { en: 'What is range advantage?', zh: '什么是范围优势?' },
      a: { en: 'The player whose range holds more strong hands on a given board has range advantage, so they can bet more often and at higher frequency.',
           zh: '在特定牌面上范围里强牌更多的一方拥有范围优势,因此可以更频繁、更高比例地下注。' } },
    { q: { en: 'How is nut advantage different from range advantage?', zh: '坚果优势和范围优势有何不同?' },
      a: { en: 'Nut advantage is holding the very top of the range — sets, straights, nut flushes — more often than the opponent. It is what lets you use big bets and overbets credibly.',
           zh: '坚果优势指你比对手更常拿到范围顶端(暗三条、顺子、坚果同花),这才是让你能可信地使用大注和超池的原因。' } },
  ],
  c4: [
    { q: { en: 'What is board texture in poker?', zh: '什么是牌面纹理?' },
      a: { en: 'Board texture describes how connected and coordinated the community cards are. Dry boards (like K-7-2 rainbow) favor the aggressor; wet, connected boards shift equity toward the caller.',
           zh: '牌面纹理描述公共牌的连接与配合程度。干燥牌面(如 K-7-2 彩虹)偏向进攻方;湿润、连接的牌面把胜率推向跟注方。' } },
    { q: { en: 'Should you c-bet more on dry or wet boards?', zh: '干燥还是湿润牌面该更多持续下注?' },
      a: { en: 'You can c-bet a higher frequency on dry boards because your opponent connects less often; on wet boards you bet a tighter, more polarized range and size up.',
           zh: '干燥牌面可以更高频率持续下注,因为对手更少击中;湿润牌面则用更窄、更极化的范围下注并加大尺寸。' } },
  ],
  c5: [
    { q: { en: 'What is a continuation bet (c-bet)?', zh: '什么是持续下注(c-bet)?' },
      a: { en: 'A c-bet is a bet made by the preflop aggressor on the flop. In position on a dry board you can c-bet a wide range small, applying pressure with both value and air.',
           zh: '持续下注是翻前加注者在翻牌圈继续下注。有位置、在干燥牌面上可以用较宽范围小注,用价值牌和空气牌同时施压。' } },
    { q: { en: 'When should you check back instead of c-betting?', zh: '什么时候该过牌而不是持续下注?' },
      a: { en: 'Check back on boards that hit the caller’s range hard, or with medium hands that prefer pot control and get little worse to call — betting there only folds out air and gets called by better.',
           zh: '在击中跟注方范围的牌面、或用偏好控池的中等牌时该过牌——此时下注只会赶走空气牌、被更好的牌跟注。' } },
  ],
  c6: [
    { q: { en: 'How do you defend out of position against a c-bet?', zh: '无位置如何防守持续下注?' },
      a: { en: 'Mix check-call with your bluff-catchers and marginal made hands, check-raise with strong hands and some semi-bluffs, and fold the bottom — defending at least the MDF so the bettor can’t auto-profit.',
           zh: '用抓诈牌和边缘成牌过牌-跟注,用强牌和部分半诈唬过牌-加注,弃掉最弱的——至少防守到 MDF,让下注方无法自动盈利。' } },
    { q: { en: 'How wide should you defend versus a half-pot c-bet?', zh: '面对半池持续下注该防守多宽?' },
      a: { en: 'Against a half-pot bet MDF is about 67%, so you continue with roughly two-thirds of your range — though against tight, value-heavy bettors you can over-fold exploitatively.',
           zh: '面对半池下注 MDF 约 67%,即大约继续三分之二的范围——不过面对偏价值的紧凶下注者,可以剥削性地多弃牌。' } },
  ],
  c7: [
    { q: { en: 'What is a polarized betting range?', zh: '什么是极化下注范围?' },
      a: { en: 'A polarized range is made up of strong value hands and bluffs, with medium hands checked. Big bets and overbets should be polarized so the bluffs are backed by real value.',
           zh: '极化范围由强价值牌和诈唬组成,中等牌过牌。大注和超池应当极化,让诈唬有真实的价值牌支撑。' } },
    { q: { en: 'What is bluff-catching?', zh: '什么是抓诈?' },
      a: { en: 'Bluff-catching is calling with a hand that beats only the opponent’s bluffs. You keep enough bluff-catchers to meet the MDF and pick the ones that block the opponent’s value hands.',
           zh: '抓诈是用只能击败对手诈唬的牌跟注。你保留足够的抓诈牌以满足 MDF,并优先选择阻断对手价值牌的组合。' } },
  ],
  c8: [
    { q: { en: 'What does indifference mean in GTO poker?', zh: 'GTO 里的「无差异」是什么意思?' },
      a: { en: 'At equilibrium the opponent is often made indifferent — their bluff-catcher wins and loses the same on average, so calling and folding have equal EV. That is why balanced ranges mix actions.',
           zh: '在均衡点对手常被逼到无差异——其抓诈牌平均输赢相同,跟注与弃牌 EV 相等。这正是平衡范围会混合行动的原因。' } },
    { q: { en: 'When should you use a mixed strategy?', zh: '什么时候该用混合策略?' },
      a: { en: 'Mix when two lines tie in EV — for example betting a hand part of the time and checking it the rest — which keeps your ranges balanced and hard to exploit.',
           zh: '当两条行动线 EV 相同时混合——例如一手牌一部分时间下注、其余时间过牌——以保持范围平衡、难被剥削。' } },
  ],
  c9: [
    { q: { en: 'What is barreling in poker?', zh: '什么是「开火/连续下注」(barrel)?' },
      a: { en: 'Barreling is continuing to bet on the next street after a c-bet. On the turn, keep barreling cards that improve your range or add equity, and give up cards that favor the caller.',
           zh: '「开火」是持续下注后在下一条街继续下注。转牌上,在提升你范围或增加胜率的牌上继续开火,在偏向跟注方的牌上放弃。' } },
    { q: { en: 'Which turn cards are good to fire a second barrel?', zh: '哪些转牌适合打第二枪?' },
      a: { en: 'Cards that strengthen your range and weaken the caller’s — overcards to the flop, cards that complete your draws, or scare cards you represent credibly — make the best second barrels.',
           zh: '能强化你范围、削弱跟注方范围的牌——翻牌之上的高牌、补齐你听牌的牌、或你能可信代表的吓人牌——最适合打第二枪。' } },
  ],
  c10: [
    { q: { en: 'How do you size a river value bet?', zh: '河牌价值下注该下多大?' },
      a: { en: 'Size to the worse hands that will call. Thin value wants a smaller bet that gets called by more marginal hands; a strong, polarized range can bet big or overbet.',
           zh: '按会跟注的更差牌来定尺寸。薄价值用较小注让更多边缘牌跟注;强而极化的范围可以大注或超池。' } },
    { q: { en: 'How many bluffs should you have on the river?', zh: '河牌该带多少诈唬?' },
      a: { en: 'Balance bluffs to value by bet size: a pot-sized bet mixes roughly one bluff for every two value hands, and bigger bets need fewer bluffs. Pick bluffs that block the opponent’s calls.',
           zh: '按下注尺寸平衡诈唬与价值:底池大小的下注大约每两手价值配一手诈唬,越大注需要的诈唬越少。优先选阻断对手跟注的诈唬。' } },
  ],
  c11: [
    { q: { en: 'When should you check-raise the flop?', zh: '什么时候该翻牌过牌-加注?' },
      a: { en: 'Check-raise out of position with strong made hands and high-equity semi-bluffs on boards that hit your range — it builds the pot with value and denies the c-bettor a cheap continue.',
           zh: '无位置、在击中你范围的牌面上,用强成牌和高胜率半诈唬过牌-加注——既用价值做大底池,又不让持续下注方廉价继续。' } },
    { q: { en: 'What is a probe bet?', zh: '什么是试探下注(probe)?' },
      a: { en: 'A probe bet is a lead by the out-of-position player on a later street after the preflop aggressor checks back — attacking the range they capped by declining to c-bet.',
           zh: '试探下注是无位置玩家在翻前加注者过牌放弃后、于后续街道率先下注——攻击对手因放弃持续下注而封顶的范围。' } },
  ],
  c12: [
    { q: { en: 'What is SPR (stack-to-pot ratio)?', zh: '什么是 SPR(筹码底池比)?' },
      a: { en: 'SPR is the effective stack divided by the pot on the flop. Low SPR (under ~4) means top pair is often committed; high SPR rewards implied odds and careful pot control.',
           zh: 'SPR 是翻牌时有效筹码除以底池。低 SPR(约 4 以下)时顶对常常已经承诺;高 SPR 则奖励隐含赔率与谨慎的控池。' } },
    { q: { en: 'How does SPR change how you play top pair?', zh: 'SPR 如何改变你打顶对的方式?' },
      a: { en: 'At low SPR you can stack off top pair profitably; at high SPR the same hand prefers pot control, because getting all-in usually means you’re beaten.',
           zh: '低 SPR 时顶对可以盈利地全下;高 SPR 时同一手牌更偏好控池,因为把筹码全打进去通常意味着你已落后。' } },
  ],
  c13: [
    { q: { en: 'How does bet sizing affect MDF?', zh: '下注尺寸如何影响 MDF?' },
      a: { en: 'Bigger bets lower the defender’s MDF and demand more equity to call, but they also require more bluffs to stay balanced. Small bets let you bet a wider range at high frequency.',
           zh: '越大的下注降低防守方的 MDF、要求更多胜率才跟注,但也需要更多诈唬来保持平衡。小注则让你能高频用更宽范围下注。' } },
    { q: { en: 'When should you use a small bet vs a big bet?', zh: '何时用小注、何时用大注?' },
      a: { en: 'Use small bets to deny equity cheaply and bet a wide range on boards you own; use big bets and overbets with a polarized range when you hold a nut advantage.',
           zh: '在你占优的牌面上用小注廉价否定胜率、下注宽范围;拥有坚果优势时用极化范围的大注与超池。' } },
  ],
  c14: [
    { q: { en: 'What are blockers in poker?', zh: '扑克里的阻断牌是什么?' },
      a: { en: 'Blockers are cards in your hand that reduce the combinations of hands your opponent can hold. Holding the ace of a suit, for example, makes the nut flush less likely for them.',
           zh: '阻断牌是你手中能减少对手可能组合的牌。例如握着某花色的 A,就降低了对手拿到坚果同花的可能。' } },
    { q: { en: 'How do blockers help you pick bluffs?', zh: '阻断牌如何帮你选诈唬?' },
      a: { en: 'The best bluffs block the opponent’s value and calling hands while unblocking their folds — so you fire hands that make it less likely they hold a call.',
           zh: '最好的诈唬阻断对手的价值牌和跟注牌、同时不阻断其弃牌——即优先用让对手更不可能跟注的组合去诈唬。' } },
  ],
  c15: [
    { q: { en: 'What should you do when your c-bet gets raised?', zh: '持续下注被加注该怎么办?' },
      a: { en: 'Fold your weakest air, continue with strong made hands and good draws, and 3-bet the flop with your best value and select semi-bluffs — raises are usually value-heavy, so respect them.',
           zh: '弃掉最弱的空气牌,用强成牌和好听牌继续,用最好的价值牌和精选半诈唬再加注——加注通常偏价值,要给予尊重。' } },
    { q: { en: 'How often are flop check-raises bluffs?', zh: '翻牌过牌-加注有多少是诈唬?' },
      a: { en: 'A balanced check-raiser mixes value and semi-bluffs, but many players are under-bluffed on the flop — against them you can fold marginal hands more than GTO suggests.',
           zh: '平衡的过牌-加注会混合价值与半诈唬,但很多玩家翻牌诈唬不足——面对他们可以比 GTO 建议更多地弃掉边缘牌。' } },
  ],
  c16: [
    { q: { en: 'How does postflop play change in a 3-bet pot?', zh: '3-bet 底池翻后打法有何不同?' },
      a: { en: 'Ranges are narrower and stronger and the SPR is lower, so equities run closer and stacks go in faster. C-bets are frequent and top pair is often committed.',
           zh: '范围更窄更强、SPR 更低,因此胜率更接近、筹码进锅更快。持续下注频率高,顶对常常已经承诺。' } },
    { q: { en: 'Should you c-bet more in single-raised or 3-bet pots?', zh: '单加注底池还是 3-bet 底池该更多持续下注?' },
      a: { en: 'The low SPR of a 3-bet pot supports frequent, often larger c-bets because both ranges are strong and there is less room to maneuver on later streets.',
           zh: '3-bet 底池的低 SPR 支持频繁、往往更大的持续下注,因为双方范围都强、后续街道的操作空间更小。' } },
  ],
  c17: [
    { q: { en: 'What is pot control in poker?', zh: '什么是底池控制?' },
      a: { en: 'Pot control means checking medium-strength hands to keep the pot small, avoiding bloating it into spots where you’re only called by better and folded on by worse.',
           zh: '底池控制是指用中等牌力过牌把底池保持小,避免把它打大到只被更好的牌跟注、被更差的牌弃掉的局面。' } },
    { q: { en: 'Which hands are best for pot control?', zh: '哪些牌最适合控池?' },
      a: { en: 'Medium made hands like second pair or a weak top pair — strong enough to win at showdown but too weak to want three streets of value — are the classic pot-control candidates.',
           zh: '中等成牌如第二对或弱顶对——足够在摊牌获胜、又不够强到想要三条街价值——是经典的控池对象。' } },
  ],
  c18: [
    { q: { en: 'How do you defend against a turn barrel?', zh: '如何防守转牌第二枪?' },
      a: { en: 'Continue with hands that still beat bluffs or have equity to improve, fold hands that lost their equity on the turn card, and stay near the MDF against balanced opponents.',
           zh: '用仍能击败诈唬或有胜率提升的牌继续,弃掉在转牌失去胜率的牌,面对平衡对手时保持在 MDF 附近。' } },
    { q: { en: 'Should you call flop planning to fold most turns?', zh: '翻牌跟注、计划大多数转牌弃牌,合理吗?' },
      a: { en: 'Sometimes — many turn cards let you fold correctly — but pick flop calls with equity or good turn coverage so you’re not forced to over-fold and become exploitable.',
           zh: '有时可以——很多转牌让你能正确弃牌——但要选有胜率或转牌覆盖好的牌翻牌跟注,以免被迫过度弃牌而变得可被剥削。' } },
  ],
  c19: [
    { q: { en: 'What is floating in poker?', zh: '什么是漂牌(float)?' },
      a: { en: 'Floating is calling a c-bet with a weak or drawing hand, planning to take the pot away on a later street when the aggressor checks or the board changes in your favor.',
           zh: '漂牌是用弱牌或听牌跟注持续下注,计划在后续街道对手过牌或牌面对你有利时把底池抢过来。' } },
    { q: { en: 'When does delayed aggression work best?', zh: '延迟进攻何时效果最好?' },
      a: { en: 'It works when the preflop aggressor c-bets a wide range then gives up — checking the turn caps their range, and a well-chosen probe or float bet attacks that weakness.',
           zh: '当翻前加注者用宽范围持续下注后放弃时最有效——转牌过牌封顶了他的范围,精选的试探或漂牌下注正好攻击这个弱点。' } },
  ],
  c20: [
    { q: { en: 'What is an overbet and when is it used?', zh: '什么是超池下注,何时使用?' },
      a: { en: 'An overbet is a bet larger than the pot. Use it with a polarized range — strong value plus bluffs — on cards and boards where you hold the nut advantage and the opponent’s range is capped.',
           zh: '超池下注是大于底池的下注。在你拥有坚果优势、对手范围封顶的牌与牌面上,用极化范围(强价值 + 诈唬)使用它。' } },
    { q: { en: 'Why do overbets need a nut advantage?', zh: '为什么超池需要坚果优势?' },
      a: { en: 'Overbetting risks a lot, so it needs the top of the range to be credible. Without nut advantage a large bet is easy to bluff-catch and re-raise, turning it into a losing play.',
           zh: '超池风险很大,需要范围顶端来使其可信。没有坚果优势时大注容易被抓诈和再加注,反而成为亏损打法。' } },
  ],
  c21: [
    { q: { en: 'What is a donk bet?', zh: '什么是领先下注(donk bet)?' },
      a: { en: 'A donk bet is a lead by the out-of-position player into the preflop aggressor, betting before giving them the chance to c-bet. It is used mainly on boards that hit the caller’s range harder.',
           zh: '领先下注是无位置玩家在翻前加注者持续下注之前率先下注。主要用在更击中跟注方范围的牌面上。' } },
    { q: { en: 'Are donk bets a good idea?', zh: '领先下注是好主意吗?' },
      a: { en: 'Usually check to the aggressor, but a small donk lead is correct on boards that shift equity to the caller — low, connected flops the raiser misses often. Keep the range balanced with value and draws.',
           zh: '通常过牌给加注者,但在把胜率推向跟注方的牌面(加注者常错过的低、连接翻牌)上,小额领先是正确的。用价值牌和听牌保持范围平衡。' } },
  ],
  c22: [
    { q: { en: 'What is a thin value bet?', zh: '什么是薄价值下注?' },
      a: { en: 'A thin value bet is betting a marginal made hand that is only slightly ahead of the hands that call. Sizing is small so worse hands still pay you off.',
           zh: '薄价值下注是用只略微领先于跟注范围的边缘成牌下注。尺寸要小,让更差的牌仍然愿意付钱。' } },
    { q: { en: 'How do you know if a hand is good enough to value bet thin?', zh: '怎么判断一手牌能否薄价值下注?' },
      a: { en: 'Ask whether worse hands will call more often than better hands raise. If your bet is called mostly by hands you beat, the thin value bet profits.',
           zh: '问自己:更差的牌跟注是否多于更好的牌加注。如果你的下注主要被你击败的牌跟注,薄价值下注就盈利。' } },
  ],
  c23: [
    { q: { en: 'What is a semi-bluff?', zh: '什么是半诈唬?' },
      a: { en: 'A semi-bluff is betting or raising with a drawing hand that can win now by making the opponent fold, and can also improve to the best hand if called — combining fold equity with real equity.',
           zh: '半诈唬是用听牌下注或加注:既能通过让对手弃牌当场获胜,被跟注后也能补牌成为最好的牌——结合了弃牌率与真实胜率。' } },
    { q: { en: 'Should you raise draws or just call?', zh: '听牌该加注还是只跟注?' },
      a: { en: 'Raise your strongest draws for fold equity and to build the pot when you hit; call with weaker draws that prefer to see cheap cards and realize equity passively.',
           zh: '用最强的听牌加注以获得弃牌率、并在击中时做大底池;用较弱的听牌跟注,偏好廉价看牌、被动兑现胜率。' } },
  ],
  c24: [
    { q: { en: 'How do you defend against a triple barrel?', zh: '如何防守三条街连续下注(三枪)?' },
      a: { en: 'Keep enough bluff-catchers to meet the river MDF, prefer ones that block the opponent’s value and unblock their bluffs, and fold the hands that beat nothing but a bluff’s worst combos.',
           zh: '保留足够抓诈牌以满足河牌 MDF,优先选阻断对手价值、不阻断其诈唬的组合,弃掉只能击败诈唬中最差组合的牌。' } },
    { q: { en: 'Are big rivers bets usually value or bluff?', zh: '河牌大注通常是价值还是诈唬?' },
      a: { en: 'A balanced player weights big rivers bets toward value with a correct fraction of bluffs, but many players under-bluff large rivers — against them, over-fold your bluff-catchers.',
           zh: '平衡玩家的河牌大注偏价值、并配以正确比例的诈唬,但许多玩家在河牌大注上诈唬不足——面对他们,多弃掉抓诈牌。' } },
  ],
  c25: [
    { q: { en: 'How does multiway pot strategy differ from heads-up?', zh: '多人底池策略与单挑有何不同?' },
      a: { en: 'With more players in the pot, someone connects more often, so you bluff far less and continue only with stronger hands. Value bets also need to be stronger to bet for value.',
           zh: '底池里玩家更多时,总有人更容易击中,所以诈唬要大幅减少、只用更强的牌继续。价值下注也需要更强的牌才值得下。' } },
    { q: { en: 'Should you c-bet multiway?', zh: '多人底池该持续下注吗?' },
      a: { en: 'C-bet a tighter, more value-weighted range multiway. With more players to get through, thin bluffs lose money and strong hands prefer to bet for value and protection.',
           zh: '多人底池用更紧、更偏价值的范围持续下注。要过的玩家更多,薄诈唬会亏钱,而强牌更偏好为价值和保护下注。' } },
  ],
  c26: [
    { q: { en: 'What are exploitative adjustments?', zh: '什么是剥削性调整?' },
      a: { en: 'Exploitative play deviates from balanced GTO to attack a specific opponent’s mistakes — over-folding against players who under-bluff, or bluffing more against players who over-fold.',
           zh: '剥削性打法偏离平衡 GTO,专门攻击特定对手的错误——面对诈唬不足的玩家多弃牌,面对过度弃牌的玩家多诈唬。' } },
    { q: { en: 'When should you deviate from GTO?', zh: '什么时候该偏离 GTO?' },
      a: { en: 'Deviate once you have a read: GTO is the un-exploitable baseline, but the money comes from adjusting to how your specific opponent is actually over- or under-doing an action.',
           zh: '有了读牌信息就偏离:GTO 是不可被剥削的基准,但利润来自根据特定对手实际上过度或不足做某个行动来调整。' } },
  ],
  c27: [
    { q: { en: 'How does ICM change postflop tournament play?', zh: 'ICM 如何改变锦标赛翻后打法?' },
      a: { en: 'ICM makes busting out costlier than chips won, so you play tighter near pay jumps and bubbles — avoiding thin stack-offs the pure-chip (cash) math would call correct.',
           zh: 'ICM 让出局的代价高于赢得的筹码,因此在奖金跳档和 bubble 附近打得更紧——避免那些纯筹码(现金局)数学会认为正确的薄全下。' } },
    { q: { en: 'Why play tighter on the bubble?', zh: '为什么在 bubble 上要打得更紧?' },
      a: { en: 'On the bubble the risk of busting just before the money outweighs the reward of extra chips, so marginal spots that are break-even in chips become clear folds under ICM.',
           zh: '在 bubble 上,进钱前出局的风险大于额外筹码的回报,所以那些按筹码算持平的边缘局面在 ICM 下变成明确的弃牌。' } },
  ],
  c28: [
    { q: { en: 'What is multi-street planning?', zh: '什么是多街计划?' },
      a: { en: 'Multi-street planning means deciding your line for the flop, turn, and river before you bet — which turn and river cards you’ll keep betting, which you’ll check, and how stacks get in.',
           zh: '多街计划是指在下注前就规划好翻牌、转牌、河牌的行动线——哪些转牌河牌继续下注、哪些过牌、以及筹码如何进锅。' } },
    { q: { en: 'Why plan the whole hand before betting the flop?', zh: '为什么下翻牌注之前要规划整手牌?' },
      a: { en: 'Betting without a plan leads to spots where you’ve bloated the pot with no good turn or river to continue. Planning ahead picks bets that set up profitable later streets.',
           zh: '没有计划就下注会导致把底池打大、却没有好的转牌河牌继续。提前规划能选出为后续街道盈利做铺垫的下注。' } },
  ],
  c29: [
    { q: { en: 'How do paired and monotone boards change strategy?', zh: '配对与同色牌面如何改变策略?' },
      a: { en: 'Paired boards reduce the number of strong hands, favoring aggression and thinner value; monotone boards let flushes appear, so the player with more of the top suit gets the nut advantage.',
           zh: '配对牌面减少了强牌数量,偏向进攻和更薄的价值;同色牌面让同花出现,因此拥有更多顶级花色的一方获得坚果优势。' } },
    { q: { en: 'Should you bet more or less on scary boards?', zh: '在吓人牌面上该多下注还是少下注?' },
      a: { en: 'It depends on who the texture favors. Bet more when the scare card is better for your range than your opponent’s; slow down when it hits the caller and caps your own range.',
           zh: '取决于纹理对谁有利。当吓人牌对你的范围比对手更好时多下注;当它击中跟注方并封顶你自己的范围时放慢。' } },
  ],
  c30: [
    { q: { en: 'What does the capstone cover?', zh: '综合实战涵盖什么?' },
      a: { en: 'The capstone mixes advanced spots across every concept — board texture, MDF, polarization, blockers, SPR, and multi-street planning — so you apply the whole framework under realistic pressure.',
           zh: '综合实战混合了跨所有概念的进阶局面——牌面纹理、MDF、极化、阻断牌、SPR 与多街计划——让你在真实压力下运用整套框架。' } },
    { q: { en: 'Is this trainer enough to improve real postflop play?', zh: '这个训练器足以提升真实翻后水平吗?' },
      a: { en: 'Repeated, verified drills with computed feedback build the pattern recognition that transfers to the table. Pair the drills with reviewing your own hands for the fastest improvement.',
           zh: '带计算式反馈的反复、验证过的训练能建立可迁移到牌桌的模式识别。把训练与复盘自己的牌局结合,进步最快。' } },
  ],
};
